packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - esbuild
  - sharp
  - supabase
  - unrs-resolver
  - workerd

ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
  - svelte-preprocess
